service: inmobiliaria-backend
frameworkVersion: '3'
useDotenv: true

provider:
    name: aws
    runtime: nodejs18.x
    memorySize: ${self:custom.MEMORYSIZE.${self:provider.stage}}
    timeout: 30
    stage: ${opt:stage,'dev'}
    region: us-east-1
    apiGateway:
        shouldStartNameWithService: true

package:
    excludeDevDependencies: true
    patterns:
        - '!**'
        - 'server.js'
        - 'lambda.js'
custom:
    stages:
        - dev
        - qas
        - prd
    MEMORYSIZE:
        dev: ${ssm:LAMBDA_MEMORYSIZE_${upper(${self:provider.stage})}}
        qas: ${ssm:LAMBDA_MEMORYSIZE_${upper(${self:provider.stage})}}
        prd: ${ssm:LAMBDA_MEMORYSIZE_${upper(${self:provider.stage})}}
functions:
    api:
        handler: lambda.handler
        events:
            - http:
                  path: /
                  method: ANY
            - http:
                  path: /{proxy+}
                  method: ANY
        layers:
            - arn:aws:lambda:us-east-1:754881596744:layer:inmobiliaria-backend:2
        
plugins:
    - serverless-stage-manager
    - serverless-plugin-utils
